version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psu_bus_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules # ป้องกันไม่ให้ node_modules ในเครื่องไปทับใน Container
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # <--- บรรทัดนี้สำคัญมาก! มันคือการทำ Anonymous Volume 
    depends_on:
      - backend

volumes:
  db_data:
